version: '3'
services:
  db:
    image: postgres:13.11
    environment:
      - POSTGRES_PASSWORD=&r1OkBP91i9f
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app
    volumes:
      - ./db-data:/var/lib/postgresql/itsdonatedata

  app1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - PGPASSWORD=&r1OkBP91i9f
      - PGUSER=postgres
      - PGDATABASE=app
      - PGHOST=db
      - PORT=3000
    depends_on:
      - db
    command: ['yarn', 'start:dev']

  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
